//pack
var global_topicModelData = {};
var global_topicResearchPackObject = {};
var global_personPackObject = null;

//tree
var toggleTreeNodeFromExternalEvent = null;
var global_selectedTreeNode = null;
var cleanNodeOfActiveStatus = null;
var collapseNotSelectedNodes = null;
var collapseAllNodesToCountry = null;

//bc
var global_bcGrantData = []; //global grant data of barchart
var global_barchartObject = {}; //global reference object for instance generated by keyedBarchart_v004.js